### ISSUE TITLE
Can't install through composer

### ISSUE THREAD

**Issue by 1llusion** [DenisOgr/yii2-cronjobs#1]
Hello,

whenever I try to install yii2-cronjobs via composer, I get the following error message:
`Problem 1
    - The requested package denisog/yii2-cronjobs could not be found in any version, there may be a typo in the package name.`

**Comment by DenisOgr** [comment]
Can you show me your composer.json file, please?

**Comment by DenisOgr** [comment]
I fixed this bug. Please, read README and try again.

**Comment by 1llusion** [comment]
Yup that works. Thanks :)
